// <auto-generated />
using System;
using APISimulacaoEmprestimo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APISimulacaoEmprestimo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250407145411_CriandoBancoDeDados")]
    partial class CriandoBancoDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APISimulacaoEmprestimo.Models.PaymentFlowSummaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MonthlyPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropostaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId")
                        .IsUnique();

                    b.ToTable("PaymentFlowSummary");
                });

            modelBuilder.Entity("APISimulacaoEmprestimo.Models.PaymentScheduleItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("PaymentFlowSummaryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentFlowSummaryId");

                    b.ToTable("PaymentScheduleItem");
                });

            modelBuilder.Entity("APISimulacaoEmprestimo.Models.PropostaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proposta");
                });

            modelBuilder.Entity("APISimulacaoEmprestimo.Models.PaymentFlowSummaryModel", b =>
                {
                    b.HasOne("APISimulacaoEmprestimo.Models.PropostaModel", "Proposta")
                        .WithOne("PaymentFlowSummary")
                        .HasForeignKey("APISimulacaoEmprestimo.Models.PaymentFlowSummaryModel", "PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("APISimulacaoEmprestimo.Models.PaymentScheduleItemModel", b =>
                {
                    b.HasOne("APISimulacaoEmprestimo.Models.PaymentFlowSummaryModel", "PaymentFlowSummary")
                        .WithMany("PaymentScheduleItem")
                        .HasForeignKey("PaymentFlowSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentFlowSummary");
                });

            modelBuilder.Entity("APISimulacaoEmprestimo.Models.PaymentFlowSummaryModel", b =>
                {
                    b.Navigation("PaymentScheduleItem");
                });

            modelBuilder.Entity("APISimulacaoEmprestimo.Models.PropostaModel", b =>
                {
                    b.Navigation("PaymentFlowSummary")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
